# Generated by Django 3.1.1 on 2020-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('rating', models.FloatField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ('-rating',),
            },
        ),
    ]
